server:
  port: 8083

spring:
  application:
    name: member-service
  datasource:
    url: jdbc:postgresql://localhost:5432/c0f
    username: c0f
    password: c0f
jwt:
  secret: my-super-secret-key-minimum-32-bytes!!!